spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    check-template: true
    check-template-location: true
  resources:
    static-locations: classpath:/