spring:
  datasource:
    url: jdbc:postgresql://localhost:8880/postgres
    username: postgres
    password: postgres
#  datasource:
#    url: ${BASE_URI}
#    username: ${BASE_USERNAME}
#    password: ${BASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    check-template: true
    check-template-location: true
  server:
    port: ${PORT}
# exclude from git