spring:
  datasource:
    url: jdbc:postgresql://localhost:8880/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    check-template: true
    check-template-location: true
    prefix: classpath:/templates
    suffix: .html
